package home.project.notebot.constants;

import lombok.Getter;

@Getter
public enum State {
    NOT_REGISTERED("NOT_REGISTERED"),
    REGISTERED("REGISTERED"),
    ADDED("ADDED"),
    REMOVABLE("REMOVABLE"),
    SEARCHING("SEARCHING"),
    TRY_IN_LOGIN("TRY_IN_LOGIN"),
    TRY_IN_PASSWORD("TRY_IN_PASSWORD"),
    TRY_REGISTRATION_LOGIN(" TRY_REGISTRATION_LOGIN"),
    TRY_REGISTRATION_PASSWORD("TRY_REGISTRATION_PASSWORD"),
    REGISTRATION_FINISHED("REGISTRATION_FINISHED"),
    ONLINE("ONLINE"),
    ADD_TITLE("ADD_TOPIC"),
    ADD_CONTENT("ADD_CONTENT"),
    ADD_CONTENT_PHOTO("ADD_CONTENT_PHOTO"),
    TIME("TIME"),
    TRY_TO_FIND("TRY_TO_FIND"),
    TRY_TO_DELETE("TRY_TO_DELETE");


    final String nameState;

    State(String nameState) {
        this.nameState = nameState;
    }
}
